from datetime import datetime
from typing import Protocol
from uuid import UUID

from src.modules.identity.domain.entities import (
    Organization,
    User,
    Workspace,
    WorkspaceMembership,
    WorkspaceRole,
)


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def create(self, *, email: str, full_name: str, password_hash: str | None) -> User: ...


class OrganizationRepository(Protocol):
    async def get_by_id(self, organization_id: UUID) -> Organization | None: ...
    async def get_by_slug(self, slug: str) -> Organization | None: ...
    async def create(self, *, name: str, slug: str) -> Organization: ...


class WorkspaceRepository(Protocol):
    async def get_by_id(self, workspace_id: UUID) -> Workspace | None: ...
    async def list_for_organization(self, organization_id: UUID) -> list[Workspace]: ...
    async def create(self, *, organization_id: UUID, name: str, slug: str) -> Workspace: ...
    async def update_name(self, workspace_id: UUID, name: str) -> Workspace: ...


class WorkspaceMembershipRepository(Protocol):
    async def get(self, workspace_id: UUID, user_id: UUID) -> WorkspaceMembership | None: ...
    async def list_for_workspace(self, workspace_id: UUID) -> list[WorkspaceMembership]: ...
    async def create(
        self, *, workspace_id: UUID, user_id: UUID, role: WorkspaceRole
    ) -> WorkspaceMembership: ...
    async def update_role(
        self, workspace_id: UUID, user_id: UUID, role: WorkspaceRole
    ) -> WorkspaceMembership: ...
    async def delete(self, workspace_id: UUID, user_id: UUID) -> None: ...


class OAuthIdentityRepository(Protocol):
    async def get_user_id_by_provider(self, provider: str, provider_uid: str) -> UUID | None: ...
    async def link(self, *, user_id: UUID, provider: str, provider_uid: str) -> None: ...


class RefreshTokenRepository(Protocol):
    async def store(self, *, user_id: UUID, token_hash: str, expires_at: datetime) -> None: ...
    async def get_active_user_id(self, token_hash: str) -> UUID | None: ...
    async def revoke(self, token_hash: str) -> None: ...
